variable "vpc_id" {}
variable "vpc_name" {}
variable "public_alb_security_group_id" {}
variable "internal_alb_security_group_id" {}
variable "public_gateway_subnet_az1_id" {}
variable "public_gateway_subnet_az2_id" {}
variable "private_proxy_subnet_az1_id" {}
variable "private_proxy_subnet_az2_id" {}
variable "private_compute_subnet_az1_id" {}
variable "private_compute_subnet_az2_id" {}